services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    env_file:
        - .env
    ports:
      # remove comment to open this port in your localhost
      # - "27017:27017"
    networks:
        - app-network
  app:
    image: app
    pull_pulicy: never
    build:
      dockerfile_inline:
        FROM node:22-alpine3.19

        WORKDIR /app

        COPY package.json package-lock.json ./

        RUN npm install

        COPY . .

        EXPOSE 3000

        CMD npm start

    container_name: app 
    restart: always
    depends_on:
        mongo
    env_file:
        - .env
    ports:
      - "3000:3000"
    networks:
        - app-network


networks:
  app-network:
    name: "app-network"

